[build]
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internal_port = 8000
auto_healthcheck = false # Désactiver l'healthcheck auto de Railway

[service.healthcheck]
path = "/health/"
interval = "30s"
timeout = "10s"
retries = 3 