[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "sh backend/railway_entrypoint.sh"
restartPolicyType = "ON_FAILURE"

[service]
internal_port = 8000
auto_healthcheck = false

[env]
DJANGO_SETTINGS_MODULE = "jaelleshop.settings"
PORT = "8000" 