[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/test/"
healthcheckTimeout = 10
healthcheckInterval = 30

[service]
internal_port = 8000
auto_healthcheck = true

[env]
DJANGO_SETTINGS_MODULE = "jaelleshop.settings"
PORT = "8000" 