version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evimeria_backend
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,${RAILWAY_PUBLIC_DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - db
    networks:
      - evimeria_network
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: evimeria_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - evimeria_network
    ports:
      - "${PORT:-8000}:80"

  db:
    image: postgres:14
    container_name: evimeria_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evimeria_network

networks:
  evimeria_network:
    driver: bridge

volumes:
  postgres_data:
  backend_static:
  backend_media: 