[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --break-system-packages -r requirements.txt && cd ../frontend && npm ci --legacy-peer-deps && npm run build && cd ../backend && python manage.py collectstatic --noinput --clear && mkdir -p staticfiles && chmod +x start_railway.sh"

[deploy]
startCommand = "cd backend && ./start_railway.sh"
# healthcheckPath = "/status/"  # TEMPORAIREMENT DÉSACTIVÉ POUR DEBUG
# healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"

[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'postgresql', 'gcc', 'nodejs']

[[services]]
name = "backend"
envs = { STATIC_DIR = "../frontend/dist" }

[[volumes]]
name = "postgres_data"
mountPath = "/var/lib/postgresql/data"
engine = "postgres" 