[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.yml"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/api-info/"
healthcheckTimeout = 300

# Service backend
[service.backend]
name = "EVIMERIA Backend"

# Volumes pour le backend
[[volume]]
name = "backend_static"
mountPath = "/app/static"
service = "backend"

[[volume]]
name = "backend_media"
mountPath = "/app/media"
service = "backend"

# Service frontend
[service.frontend]
name = "EVIMERIA Frontend"

# Volume pour la base de données
[[volume]]
name = "postgres_data"
mountPath = "/var/lib/postgresql/data"
service = "db"