[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --break-system-packages -r requirements.txt && cd ../frontend && npm ci --legacy-peer-deps && npm run build && cd ../backend && python manage.py collectstatic --noinput --clear && mkdir -p staticfiles"

[deploy]
startCommand = "cd backend && echo '🚀 EVIMERIA - Démarrage Railway' && echo 'Variables critiques:' && echo \"DATABASE_URL: ${DATABASE_URL:0:50}...\" && echo \"SECRET_KEY: ${SECRET_KEY:0:20}...\" && echo \"DEBUG: $DEBUG\" && python manage.py migrate --noinput && python -m gunicorn jaelleshop.wsgi:application --bind 0.0.0.0:$PORT --workers=2 --timeout=120 --max-requests=1000 --max-requests-jitter=100 --access-logfile=- --error-logfile=- --log-level=info"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"

[[services]]
name = "backend"
envs = { STATIC_DIR = "../frontend/dist" } 