[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --break-system-packages -r requirements.txt && cd ../frontend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && gunicorn jaelleshop.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
provider = "nixpacks"
noDocker = true

[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'postgresql', 'gcc']

[[services]]
name = "backend"
envs = { STATIC_DIR = "../frontend/dist" }

[[volumes]]
name = "postgres_data"
mountPath = "/var/lib/postgresql/data"
engine = "postgres" 